name: 💡 Sugerencia de Mejora
description: Sugerir una mejora para el repositorio
title: "[IMPROVEMENT] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ¡Nos encanta recibir sugerencias para mejorar nuestro repositorio de assets!

  - type: dropdown
    id: improvement-type
    attributes:
      label: Tipo de Mejora
      description: ¿Qué tipo de mejora sugieres?
      options:
        - Organización del repositorio
        - Nuevas convenciones de nomenclatura
        - Herramientas de automatización
        - Documentación
        - Proceso de contribución
        - Calidad de assets existentes
        - Otro
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descripción de la Mejora
      description: Describe tu sugerencia detalladamente
      placeholder: |
        Ejemplo: Sería útil tener una herramienta automatizada que optimice 
        todas las imágenes PNG cuando se suben al repositorio, para mantener 
        los tamaños de archivo pequeños sin perder calidad.
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Beneficios
      description: ¿Qué beneficios traería esta mejora?
      placeholder: |
        - Archivos más pequeños = carga más rápida
        - Proceso automatizado = menos trabajo manual
        - Consistencia en la calidad de todos los assets

  - type: textarea
    id: implementation
    attributes:
      label: Propuesta de Implementación
      description: Si tienes ideas sobre cómo implementar esto, compártelas
      placeholder: |
        Se podría usar GitHub Actions con herramientas como TinyPNG API 
        para optimizar automáticamente las imágenes en cada PR.

  - type: dropdown
    id: complexity
    attributes:
      label: Complejidad Estimada
      description: ¿Qué tan compleja crees que sería esta mejora?
      options:
        - Baja - Cambio simple
        - Media - Requiere algo de trabajo
        - Alta - Cambio significativo
        - No estoy seguro
    validations:
      required: true

  - type: checkboxes
    id: volunteer
    attributes:
      label: Participación
      options:
        - label: Estaría dispuesto a ayudar con la implementación de esta mejora